version: '3.9'

services:
  user-serivce:
    container_name: SIS-UserService
    build:
      context: .
      dockerfile: ./Backend/Services/UserService/API/Dockerfile
    ports:
      - "8082:8080"

  user-db:
    container_name: SIS-UserDB
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: database_user
      MYSQL_PASSWORD: Password1!
    ports:
      - "3307:3306"
    volumes:
      - user_db:/var/lib/mysql
  
volumes:
  user_db: