services:
  yarp-gateway:
    container_name: SIS-YARP-Gateway
    build:
      context: .
      dockerfile: ./Backend/Gateway/YARP/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - user-service
      - todo-service
      - item-service
  
  auth-service:
    container_name: SIS-AuthService
    build:
      context: .
      dockerfile: ./Backend/Services/AuthService/API/Dockerfile
    depends_on:
        - user-service
        - auth-db
    ports:
      - "8090:8091"
  
  user-service:
    container_name: SIS-UserService
    build:
      context: .
      dockerfile: ./Backend/Services/UserService/API/Dockerfile
    depends_on:
      - user-db
    ports:
      - "8091:8091" 

  todo-service:
    container_name: SIS-ListService
    build:
      context: .
      dockerfile: ./Backend/Services/ToDoService/API/Dockerfile
    depends_on:
        - user-service
        - todo-db
    ports:
      - "8092:8092"

  item-service:
    container_name: SIS-ItemService
    build:
      context: .
      dockerfile: ./Backend/Services/ItemService/API/Dockerfile
    depends_on:
        - todo-service
        - todo-db
    ports:
      - "8093:8093"

  auth-db:
    container_name: SIS-AuthDB
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: database_user
      MYSQL_PASSWORD: Password1!
    ports:
      - "3306:3306"
    volumes:
      - auth_db:/var/lib/mysql

  user-db:
    container_name: SIS-UserDB
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: database_user
      MYSQL_PASSWORD: Password1!
    ports:
      - "3307:3307"
    volumes:
      - user_db:/var/lib/mysql
        
  todo-db:
    container_name: SIS-ToDoDB
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: database_user
      MYSQL_PASSWORD: Password1!
    ports:
      - "3308:3308"
    volumes:
      - todo_db:/var/lib/mysql
  
volumes:
  auth_db:
  user_db:
  todo_db: