services:
  yarp-gateway:
    container_name: SIS-YARP-Gateway
    build:
      context: .
      dockerfile: ./Backend/Gateway/YARP-Gateway/Dockerfile
    ports:
      - "49151:8080"
    networks:
      - app-network
  
  ocelot-gateway:
    container_name: SIS-Ocelot-Gateway
    build:
      context: .
      dockerfile: ./Backend/Gateway/Ocelot-Gateway/Dockerfile
    ports:
        - "49152:8080"
    networks:
        - app-network
  
  auth-service:
    container_name: SIS-AuthService
    build:
      context: .
      dockerfile: ./Backend/Services/AuthService/API/Dockerfile
    depends_on:
        - user-service
        - auth-db
        - ocelot-gateway
        - yarp-gateway
    ports:
      - "49153:8080"
    networks:
      - app-network
  
  user-service:
    container_name: SIS-UserService
    build:
      context: .
      dockerfile: ./Backend/Services/UserService/API/Dockerfile
    depends_on:
      - user-db
      - ocelot-gateway
      - yarp-gateway
    ports:
      - "49154:8080" 
    networks:
      - app-network

  todo-service:
    container_name: SIS-ListService
    build:
      context: .
      dockerfile: ./Backend/Services/ToDoService/API/Dockerfile
    depends_on:
        - user-service
        - todo-db
        - ocelot-gateway
        - yarp-gateway
    ports:
      - "49155:8080"
    networks:
      - app-network

  item-service:
    container_name: SIS-ItemService
    build:
      context: .
      dockerfile: ./Backend/Services/ItemService/API/Dockerfile
    depends_on:
        - todo-service
        - ocelot-gateway
        - yarp-gateway
    ports:
      - "49156:8080"
    networks:
      - app-network

  auth-db:
    container_name: SIS-AuthDB
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: database_user
      MYSQL_PASSWORD: Password1!
    ports:
      - "3306:3306"
    volumes:
      - auth_db:/var/lib/mysql
    networks:
      - app-network

  user-db:
    container_name: SIS-UserDB
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: database_user
      MYSQL_PASSWORD: Password1!
    ports:
      - "3307:3306"
    volumes:
      - user_db:/var/lib/mysql
    networks:
      - app-network
        
  todo-db:
    container_name: SIS-ToDoDB
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: database_user
      MYSQL_PASSWORD: Password1!
    ports:
      - "3308:3306"
    volumes:
      - todo_db:/var/lib/mysql
    networks:
      - app-network
  
volumes:
  auth_db:
  user_db:
  todo_db:
    
networks:
  app-network:
    driver: bridge