services:
  auth-service:
    container_name: SIS-AuthService
    build:
      context: .
      dockerfile: ./Backend/Services/AuthService/API/Dockerfile
    ports:
      - "8081:8080"
  
  user-service:
    container_name: SIS-UserService
    build:
      context: .
      dockerfile: ./Backend/Services/UserService/API/Dockerfile
    ports:
      - "8082:8080" 

  todo-service:
    container_name: SIS-ListService
    build:
      context: .
      dockerfile: ./Backend/Services/ToDoService/API/Dockerfile
    ports:
      - "8083:8080"

  item-service:
    container_name: SIS-ItemService
    build:
      context: .
      dockerfile: ./Backend/Services/ItemService/API/Dockerfile
    ports:
      - "8084:8080"

  auth-db:
    container_name: SIS-AuthDB
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: database_user
      MYSQL_PASSWORD: Password1!
    ports:
      - "3306:3306"
    volumes:
      - auth_db:/var/lib/mysql

  user-db:
    container_name: SIS-UserDB
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: database_user
      MYSQL_PASSWORD: Password1!
    ports:
      - "3307:3307"
    volumes:
      - user_db:/var/lib/mysql
        
  todo-db:
    container_name: SIS-ToDoDB
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: database_user
      MYSQL_PASSWORD: Password1!
    ports:
      - "3308:3308"
    volumes:
      - todo_db:/var/lib/mysql
  
volumes:
  auth_db:
  user_db:
  todo_db: