services:
  user-service:
    container_name: SIS-UserService
    build:
      context: .
      dockerfile: ./Backend/Services/UserService/API/Dockerfile
    ports:
      - "8082:8080" 

  todo-service:
    container_name: SIS-ListService
    build:
      context: .
      dockerfile: ./Backend/Services/ToDoService/API/Dockerfile
    ports:
      - "8083:8080"

  item-service:
    container_name: SIS-ItemService
    build:
      context: .
      dockerfile: ./Backend/Services/ItemService/API/Dockerfile
    ports:
      - "8084:8080"

  user-db:
    container_name: SIS-UserDB
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: database_user
      MYSQL_PASSWORD: Password1!
    ports:
      - "3307:3306"
    volumes:
      - user_db:/var/lib/mysql
        
  todo-db:
    container_name: SIS-ToDoDB
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: database_user
      MYSQL_PASSWORD: Password1!
    ports:
      - "3308:3306"
    volumes:
      - todo_db:/var/lib/mysql
  
volumes:
  user_db:
  todo_db: